plant_data = {
    "Tomato": {
        "scientific_name": "Solanum lycopersicum",
        "type": "Fruit",
        "cycle": "Annual",
        "watering": "Moderate",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Loamy"],
        "attracts": ["Bees", "Butterflies"],
        "edible": True,
        "poisonous": False,
        "medicinal": False,
        "description": "A popular garden fruit with juicy, red berries. Requires full sun and regular watering.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/tomato.jpg"
    },
    "Carrot": {
        "scientific_name": "Daucus carota subsp. sativus",
        "type": "Root vegetable",
        "cycle": "Biennial",
        "watering": "Moderate",
        "sunlight": ["Full sun", "Partial shade"],
        "soil": ["Sandy", "Loamy"],
        "attracts": ["Pollinators"],
        "edible": True,
        "poisonous": False,
        "medicinal": True,
        "description": "A root vegetable known for its sweet, crunchy texture and bright orange color.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/carrot.jpg"
    },
    "Basil": {
        "scientific_name": "Ocimum basilicum",
        "type": "Herb",
        "cycle": "Annual",
        "watering": "Moderate",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Rich"],
        "attracts": ["Bees"],
        "edible": True,
        "poisonous": False,
        "medicinal": True,
        "description": "An aromatic herb used in cooking. Known for its fragrant leaves and ability to repel pests.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/basil.jpg"
    },
    "Lettuce": {
        "scientific_name": "Lactuca sativa",
        "type": "Leafy green",
        "cycle": "Annual",
        "watering": "Frequent",
        "sunlight": ["Full sun", "Partial shade"],
        "soil": ["Moist", "Well-draining"],
        "attracts": [],
        "edible": True,
        "poisonous": False,
        "medicinal": False,
        "description": "A fast-growing leafy vegetable commonly used in salads. Thrives in cool weather.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/lettuce.jpg"
    },
    "Strawberry": {
        "scientific_name": "Fragaria × ananassa",
        "type": "Fruit",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Slightly acidic"],
        "attracts": ["Bees", "Butterflies"],
        "edible": True,
        "poisonous": False,
        "medicinal": False,
        "description": "Produces sweet, red fruits with a juicy texture. Great for garden beds or containers.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/strawberry.jpg"
    },
    "Rosemary": {
        "scientific_name": "Salvia rosmarinus",
        "type": "Herb",
        "cycle": "Perennial",
        "watering": "Minimal",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining"],
        "attracts": ["Bees"],
        "edible": True,
        "poisonous": False,
        "medicinal": True,
        "description": "A woody herb with fragrant, needle-like leaves. Commonly used in cooking and has medicinal properties.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/rosemary.jpg"
    },
    "Pepper": {
        "scientific_name": "Capsicum annuum",
        "type": "Fruit",
        "cycle": "Annual",
        "watering": "Moderate",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Fertile"],
        "attracts": ["Bees"],
        "edible": True,
        "poisonous": False,
        "medicinal": True,
        "description": "A colorful fruit with varying levels of heat. Adds spice and flavor to dishes.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/pepper.jpg"
    },
    "Cucumber": {
        "scientific_name": "Cucumis sativus",
        "type": "Vine",
        "cycle": "Annual",
        "watering": "Frequent",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Rich"],
        "attracts": ["Bees"],
        "edible": True,
        "poisonous": False,
        "medicinal": False,
        "description": "A fast-growing vine producing crisp, refreshing fruits. Perfect for salads and pickling.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/cucumber.jpg"
    },
    "Mint": {
        "scientific_name": "Mentha",
        "type": "Herb",
        "cycle": "Perennial",
        "watering": "Frequent",
        "sunlight": ["Partial shade", "Full sun"],
        "soil": ["Moist", "Well-draining"],
        "attracts": ["Bees", "Butterflies"],
        "edible": True,
        "poisonous": False,
        "medicinal": True,
        "description": "A fast-spreading herb with a refreshing aroma. Commonly used in teas, desserts, and as a garnish.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/mint.jpg"
    },
    "Zucchini": {
        "scientific_name": "Cucurbita pepo",
        "type": "Vegetable",
        "cycle": "Annual",
        "watering": "Moderate",
        "sunlight": ["Full sun"],
        "soil": ["Well-draining", "Fertile"],
        "attracts": ["Bees"],
        "edible": True,
        "poisonous": False,
        "medicinal": False,
        "description": "A summer squash producing elongated fruits. Thrives in warm weather and benefits from regular harvesting.",
        "age": 0,
        "value": 0,
        "image_url": "/static/images/zucchini.jpg"
    }
}

personal_plant_data = {}
