plant_data = {
    "Snake Plant": {
        "scientific_name": "Dracaena trifasciata",
        "type": "Succulent",
        "cycle": "Perennial",
        "watering": "Minimal",
        "sunlight": ["Low light", "Indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "A hardy plant with upright, sword-like leaves, known for its air-purifying abilities and tolerance to low light."
    },
    "Spider Plant": {
        "scientific_name": "Chlorophytum comosum",
        "type": "Herbaceous perennial",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": False,
        "medicinal": False,
        "description": "Features arching, striped leaves and small white flowers; produces 'spiderettes' that dangle from the mother plant."
    },
    "Peace Lily": {
        "scientific_name": "Spathiphyllum",
        "type": "Flowering plant",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Low light", "Indirect light"],
        "soil": ["Moist, well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "Known for its elegant white blooms and glossy leaves; thrives in low-light conditions and helps purify indoor air."
    },
    "Pothos": {
        "scientific_name": "Epipremnum aureum",
        "type": "Vine",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Low light", "Indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "A versatile vining plant with heart-shaped leaves; tolerates low light and is easy to care for, making it ideal for beginners."
    },
    "ZZ Plant": {
        "scientific_name": "Zamioculcas zamiifolia",
        "type": "Succulent",
        "cycle": "Perennial",
        "watering": "Minimal",
        "sunlight": ["Low light", "Indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "Features glossy, deep green leaves; highly drought-tolerant and thrives in low-light environments."
    },
    "Monstera": {
        "scientific_name": "Monstera deliciosa",
        "type": "Vine",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "Known for its large, perforated leaves; adds a tropical touch to interiors and prefers bright, indirect light."
    },
    "Fiddle Leaf Fig": {
        "scientific_name": "Ficus lyrata",
        "type": "Tree",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Bright, indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "Features large, violin-shaped leaves; popular for its bold appearance but requires consistent care and ample light."
    },
    "Rubber Plant": {
        "scientific_name": "Ficus elastica",
        "type": "Tree",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Bright, indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "Known for its thick, glossy leaves; a resilient plant that can adapt to various indoor conditions."
    },
    "Bird of Paradise": {
        "scientific_name": "Strelitzia reginae",
        "type": "Flowering plant",
        "cycle": "Perennial",
        "watering": "Moderate",
        "sunlight": ["Bright, indirect light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": False,
        "medicinal": False,
        "description": "Features striking, bird-like orange and blue flowers; adds a dramatic, tropical flair to indoor spaces."
    },
    "Jade Plant": {
        "scientific_name": "Crassula ovata",
        "type": "Succulent",
        "cycle": "Perennial",
        "watering": "Minimal",
        "sunlight": ["Bright light"],
        "soil": ["Well-draining"],
        "attracts": [],
        "edible": False,
        "poisonous": True,
        "medicinal": False,
        "description": "A succulent with thick, fleshy leaves; symbolizes good luck and prosperity; thrives with minimal watering."
    }
}